# Generated by Django 6.0.3 on 2026-03-06 09:45

import cloudinary.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('provider_admin', 'Provider Admin'), ('client', 'Client'), ('driver', 'Driver'), ('staff', 'Staff')], default='client', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'custom_user',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_photo')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$', 'Enter a valid phone number.')])),
                ('can_create_users', models.BooleanField(default=False)),
                ('can_verify_profiles', models.BooleanField(default=False)),
                ('can_manage_drivers', models.BooleanField(default=True)),
                ('can_manage_providers', models.BooleanField(default=False)),
                ('can_manage_payments', models.BooleanField(default=False)),
                ('can_manage_staff', models.BooleanField(default=False)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'admin profile',
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_photo')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$', 'Enter a valid phone number.')])),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'client profile',
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_photo')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$', 'Enter a valid phone number.')])),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'staff'}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'staff profile',
            },
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_photo')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$', 'Enter a valid phone number.')])),
                ('national_id_front', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='id_front')),
                ('national_id_back', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='id_back')),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('license_expiry_date', models.DateField(blank=True, null=True)),
                ('vehicle_make', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vehicle_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_color', models.CharField(blank=True, max_length=50, null=True)),
                ('is_available', models.BooleanField(db_index=True, default=False)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0, editable=False)),
                ('total_trips', models.PositiveIntegerField(default=0, editable=False)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'driver profile',
                'indexes': [models.Index(fields=['is_verified'], name='accounts_dr_is_veri_66b8fe_idx'), models.Index(fields=['is_available'], name='accounts_dr_is_avai_3bba76_idx'), models.Index(fields=['average_rating'], name='accounts_dr_average_5a0287_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProviderAdminProfile',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_photo')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$', 'Enter a valid phone number.')])),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('company_registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('company_logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='company_logo')),
                ('company_website', models.URLField(blank=True, null=True)),
                ('office_address', models.TextField(blank=True, null=True)),
                ('office_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('tin_number', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('facebook_page', models.URLField(blank=True, null=True)),
                ('instagram_handle', models.CharField(blank=True, max_length=50, null=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0, editable=False)),
                ('total_transactions', models.PositiveIntegerField(default=0, editable=False)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'provider_admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='provider_admin_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'provider admin profile',
                'indexes': [models.Index(fields=['is_verified'], name='accounts_pr_is_veri_2afcf9_idx'), models.Index(fields=['average_rating'], name='accounts_pr_average_675494_idx')],
            },
        ),
    ]
