# Generated by Django 6.0.3 on 2026-03-12 22:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('district', models.CharField(default='Kampala', max_length=100)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.OneToOneField(blank=True, limit_choices_to={'role': 'provider_admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_make', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ambulance_type', models.CharField(choices=[('BLS', 'Basic Life Support'), ('ALS', 'Advanced Life Support'), ('ICU', 'ICU-Equipped'), ('MAT', 'Maternity'), ('NEO', 'Neonatal'), ('OFF', 'Off-Road ALS')], default='BLS', max_length=5)),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy / On Call'), ('maintenance', 'Under Maintenance'), ('offline', 'Offline')], db_index=True, default='available', max_length=15)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('base_fare', models.PositiveIntegerField(default=100000, help_text='UGX')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_ambulance', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambulances', to='ambulances.provider')),
            ],
            options={
                'ordering': ['provider', 'plate_number'],
            },
        ),
    ]
