# Generated by Django 6.0.3 on 2026-03-12 22:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambulances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('dispatched', 'Dispatched'), ('ongoing', 'Ongoing / En Route'), ('arrived', 'Arrived at Scene'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='', max_length=15)),
                ('to_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('dispatched', 'Dispatched'), ('ongoing', 'Ongoing / En Route'), ('arrived', 'Arrived at Scene'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=15)),
                ('note', models.TextField(blank=True, default='')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_phone', models.CharField(max_length=20)),
                ('patient_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('emergency_type', models.CharField(choices=[('accident', 'Accident / Trauma'), ('cardiac', 'Cardiac Emergency'), ('maternity', 'Maternity'), ('respiratory', 'Respiratory'), ('stroke', 'Stroke'), ('paediatric', 'Paediatric'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('pickup_address', models.TextField()),
                ('pickup_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destination_address', models.TextField(blank=True, default='')),
                ('destination_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destination_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('dispatched', 'Dispatched'), ('ongoing', 'Ongoing / En Route'), ('arrived', 'Arrived at Scene'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=15)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash on Arrival'), ('mtn_money', 'MTN Mobile Money'), ('airtel_money', 'Airtel Money'), ('insurance', 'Insurance')], default='cash', max_length=15)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('waived', 'Waived')], db_index=True, default='unpaid', max_length=10)),
                ('insurance_provider', models.CharField(blank=True, default='', max_length=200)),
                ('insurance_policy_ref', models.CharField(blank=True, default='', max_length=100)),
                ('base_fare', models.PositiveIntegerField(default=0)),
                ('platform_fee', models.PositiveIntegerField(default=5000)),
                ('discount', models.PositiveIntegerField(default=0, help_text='Discount amount in UGX')),
                ('total_fare', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('ongoing_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('ambulance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='ambulances.ambulance')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
