# Generated by Django 6.0.3 on 2026-03-12 22:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('hospital_type', models.CharField(choices=[('public', 'Public / Government'), ('private', 'Private'), ('ngo', 'NGO / Mission'), ('clinic', 'Clinic'), ('specialised', 'Specialised Centre')], default='private', max_length=15)),
                ('registration_no', models.CharField(blank=True, default='', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('phone_primary', models.CharField(max_length=20)),
                ('phone_emergency', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('website', models.URLField(blank=True, default='')),
                ('address', models.TextField()),
                ('district', models.CharField(db_index=True, default='Kampala', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('specialities', models.JSONField(blank=True, default=list, help_text='List of Speciality values this hospital offers.')),
                ('has_icu', models.BooleanField(default=False)),
                ('has_maternity', models.BooleanField(default=False)),
                ('has_blood_bank', models.BooleanField(default=False)),
                ('has_ambulance', models.BooleanField(default=False, help_text='Hospital operates own ambulances.')),
                ('accepts_insurance', models.BooleanField(default=False)),
                ('is_24_hours', models.BooleanField(default=False)),
                ('total_beds', models.PositiveSmallIntegerField(default=0)),
                ('available_beds', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('full', 'At Capacity'), ('emergency_only', 'Emergency Cases Only')], db_index=True, default='active', max_length=20)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Pinned at top of client search results.')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_user', models.OneToOneField(blank=True, limit_choices_to={'role': 'hospital_admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_featured', '-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HospitalReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(help_text='1–5 stars')),
                ('comment', models.TextField(blank=True, default='')),
                ('is_approved', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_review', to='bookings.booking')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hospitals.hospital')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['district', 'status'], name='hospitals_h_distric_0799e3_idx'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['is_verified', 'is_active'], name='hospitals_h_is_veri_7c5068_idx'),
        ),
    ]
